site_name: VIBE User Documentation

# Copyright footer
copyright: 'Copyright &copy; University of Bern, Data Science Lab'
# Link to repo
repo_name: 'dsl-unibe-ch/vibe-documentation'
repo_url: 'https://github.com/dsl-unibe-ch/vibe-documentation'
edit_uri: 'edit/main/docs'

use_directory_urls: false
nav:
  - The VIBE Platform:
    - Overview: the-vibe-platform/general-description.md
  - Getting Started:
    - Getting an UBELIX Account: getting-started/getting-an-ubelix-account.md
    - Quick start: getting-started/quick_start.md
    - VIBE system configuration: getting-started/vibe_configuration_form.md
  - How-To Guides:
    - Determine your Resource Needs: how-to-guides/determine-your-resource-needs.md
    - Data Management: how-to-guides/data-management.md
  - VIBE Applications:
    - Overview: vibe-applications/overview.md
    - Container: vibe-applications/container/ 
  - Examples:
    - Overview: examples/examples_overview.md
    - Segment and track with MicroSAM and TrackMate: examples/examples_cell_tracking.md
    - Deconvolution with Huygens: examples/examples_deconvolution_huygens.md
  - In-Depth Explanations:
    - Launching Applications from the Terminal: in-depth-explanations/launching-applications-from-the-terminal.md 
  - Get in touch: contact.md

# Configuration
theme:
  name: material

extra_css:
  - 'stylesheets/unibe.css'

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - search
  - literate-nav:
      nav_file: SUMMARY.md

# See https://python-markdown.github.io/extensions/ and
# See https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions#Bundles
#     https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - sane_lists
  - smarty
  - tables
  - toc

# Social links bottom right
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dsl-unibe-ch
